modLoader="javafml"
loaderVersion="[36,)"
license="GPLv3"
issueTrackerURL="https://github.com/uecasm/colony4cc/issues"
[[mods]]
modId="colony4cc"
version="${version}"
displayName="MineColonies for ComputerCraft"
updateJSONURL="https://raw.githubusercontent.com/uecasm/colony4cc/trunk/update.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/minecolonies-for-computercraft"
logoFile="logo.png"
credits="ComputerCraft addon for MineColonies"
authors="Mirality"
description='''
This provides a basic ComputerCraft-accessible peripheral for MineColonies.
'''
[[dependencies.colony4cc]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.colony4cc]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
[[dependencies.colony4cc]]
    modId="computercraft"
    mandatory=true
    versionRange="[1.97.0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.colony4cc]]
    modId="minecolonies"
    mandatory=true
    versionRange="[0.14.315-ALPHA,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.colony4cc]]
    modId="jei"
    mandatory=false
    versionRange="[7.6.4,)"
    ordering="NONE"
    side="CLIENT"
